#!/bin/bash

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file
sudo sed -i 's/localhost$/localhost\n127.0.0.2/' /etc/hosts
sudo sed -i 's/facebook.com$/facebook.com\n8.8.8.8/' /etc/hosts

# Flush DNS cache
sudo systemctl restart systemd-resolved
